// <auto-generated />
using System;
using CoffeeCo.StoreLib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CoffeeCo.UI.MigrServPostgresql.Migrations
{
    [DbContext(typeof(StoreContext))]
    [Migration("20260219235058_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CoffeeCo.StoreLib.Models.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<long>("Add_Number")
                        .HasColumnType("bigint");

                    b.Property<string>("County")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<int?>("NationalAddressId")
                        .HasColumnType("integer");

                    b.Property<string>("Plus_4")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<int>("StateId")
                        .HasColumnType("integer");

                    b.Property<string>("StreetName")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("character varying(60)");

                    b.Property<string>("Zip_Code")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.HasKey("Id");

                    b.HasIndex("StateId");

                    b.ToTable("Address");
                });

            modelBuilder.Entity("CoffeeCo.StoreLib.Models.NationalAddress", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AddAuth")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("AddNum_Pre")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("AddNum_Suf")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Addr_Type")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int?>("AddressId")
                        .HasColumnType("integer");

                    b.Property<string>("Addtl_Loc")
                        .HasMaxLength(225)
                        .HasColumnType("character varying(225)");

                    b.Property<string>("Building")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Bulk_Plus4")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<string>("Bulk_Zip")
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)");

                    b.Property<DateTime?>("Effective")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("Expired")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Floor")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<Guid>("GUID")
                        .HasColumnType("uuid");

                    b.Property<string>("Inc_Muni")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LandmkName")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("LandmkPart")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("LastUpdate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<float>("Lat")
                        .HasColumnType("real");

                    b.Property<float>("Long")
                        .HasColumnType("real");

                    b.Property<string>("Milepost")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("NatGrid_Coord")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Nbrhd_Comm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Placement")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("Post_Comm")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)");

                    b.Property<string>("Room")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("StN_PosDir")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("StN_PosMod")
                        .HasMaxLength(25)
                        .HasColumnType("character varying(25)");

                    b.Property<string>("StN_PosTyp")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("StN_PreDir")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("StN_PreMod")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("StN_PreSep")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("StN_PreTyp")
                        .HasMaxLength(15)
                        .HasColumnType("character varying(15)");

                    b.Property<string>("Uninc_Comm")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("UniqWithin")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.Property<string>("Unit")
                        .HasMaxLength(75)
                        .HasColumnType("character varying(75)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId")
                        .IsUnique();

                    b.ToTable("NationalAddresses");
                });

            modelBuilder.Entity("CoffeeCo.StoreLib.Models.StatePossession", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Abbreviation")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("character varying(2)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("StatePossessions");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Abbreviation = "AL",
                            Value = "Alabama"
                        },
                        new
                        {
                            Id = 2,
                            Abbreviation = "AK",
                            Value = "Alaska"
                        });
                });

            modelBuilder.Entity("CoffeeCo.StoreLib.Models.Address", b =>
                {
                    b.HasOne("CoffeeCo.StoreLib.Models.StatePossession", "State")
                        .WithMany("Addresses")
                        .HasForeignKey("StateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("State");
                });

            modelBuilder.Entity("CoffeeCo.StoreLib.Models.NationalAddress", b =>
                {
                    b.HasOne("CoffeeCo.StoreLib.Models.Address", "Address")
                        .WithOne("NationalAddress")
                        .HasForeignKey("CoffeeCo.StoreLib.Models.NationalAddress", "AddressId");

                    b.Navigation("Address");
                });

            modelBuilder.Entity("CoffeeCo.StoreLib.Models.Address", b =>
                {
                    b.Navigation("NationalAddress");
                });

            modelBuilder.Entity("CoffeeCo.StoreLib.Models.StatePossession", b =>
                {
                    b.Navigation("Addresses");
                });
#pragma warning restore 612, 618
        }
    }
}
