// <auto-generated />
using System;
using CoffeeCo.UILib.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CoffeeCo.UI.MigrServSqlServer.Migrations
{
    [DbContext(typeof(UIConfigContext))]
    [Migration("20260217014207_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeCo.UILib.Models.HomeItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeRowId")
                        .HasColumnType("int");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("HomeRowId");

                    b.ToTable("HomeItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeRowId = 1,
                            Text = "Hello World"
                        });
                });

            modelBuilder.Entity("CoffeeCo.UILib.Models.HomeList", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Active")
                        .HasColumnType("bit");

                    b.Property<int>("Cols")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("Updated")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("HomeLists");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Active = true,
                            Cols = 2,
                            Created = new DateTime(2026, 2, 17, 1, 42, 7, 515, DateTimeKind.Utc).AddTicks(5264),
                            StartDate = new DateTime(2026, 2, 17, 1, 42, 7, 515, DateTimeKind.Utc).AddTicks(5064),
                            Updated = new DateTime(2026, 2, 17, 1, 42, 7, 515, DateTimeKind.Utc).AddTicks(5352)
                        });
                });

            modelBuilder.Entity("CoffeeCo.UILib.Models.HomeRow", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("HomeListId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HomeListId");

                    b.ToTable("HomeRows");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            HomeListId = 1
                        });
                });

            modelBuilder.Entity("CoffeeCo.UILib.Models.HomeItem", b =>
                {
                    b.HasOne("CoffeeCo.UILib.Models.HomeRow", "HomeRow")
                        .WithMany("HomeItems")
                        .HasForeignKey("HomeRowId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeRow");
                });

            modelBuilder.Entity("CoffeeCo.UILib.Models.HomeRow", b =>
                {
                    b.HasOne("CoffeeCo.UILib.Models.HomeList", "HomeList")
                        .WithMany("HomeRows")
                        .HasForeignKey("HomeListId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HomeList");
                });

            modelBuilder.Entity("CoffeeCo.UILib.Models.HomeList", b =>
                {
                    b.Navigation("HomeRows");
                });

            modelBuilder.Entity("CoffeeCo.UILib.Models.HomeRow", b =>
                {
                    b.Navigation("HomeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
